# Generated by Django 4.1.7 on 2023-03-21 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capiclean', '0002_alter_register_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Email', models.CharField(max_length=20)),
                ('Phone', models.IntegerField()),
                ('Message', models.CharField(max_length=100)),
            ],
        ),
    ]
