# Generated by Django 4.1.7 on 2023-03-25 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capiclean', '0004_carrer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Email', models.CharField(max_length=20)),
                ('Address', models.CharField(max_length=100)),
                ('Phone', models.IntegerField()),
            ],
        ),
    ]
