# Generated by Django 4.1.7 on 2023-03-25 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capiclean', '0005_apply'),
    ]

    operations = [
        migrations.AddField(
            model_name='apply',
            name='CV',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
